# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1225809385);
user_pref("app.update.lastUpdateTime.background-update-timer", 1225809385);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1225809385);
user_pref("calendar.autorefresh.timeout", 30);
user_pref("calendar.categories.names", "Anniversary,Birthday,Business,Calls,Clients,Competition,Customer,Favorites,Follow up,Gifts,Holidays,Ideas,Issues,Miscellaneous,Personal,Projects,Public Holiday,Status,Suppliers,Travel,Vacation");
user_pref("calendar.preferences.lightning.selectedTabIndex", 0);
user_pref("extensions.update.notifyUser", false);
user_pref("ldap_2.prefs_migrated", true);
user_pref("ldap_2.servers.OracleDirectory.auth.savePassword", true);
user_pref("ldap_2.servers.OracleDirectory.description", "Oracle Directory");
user_pref("ldap_2.servers.OracleDirectory.filename", "abook.mab");
user_pref("ldap_2.servers.OracleDirectory.replication.lastChangeNumber", 0);
user_pref("ldap_2.servers.OracleDirectory.uri", "ldaps://ldap.oracle.com:636/dc=oracle,dc=com??sub");
user_pref("ldap_2.servers.default.filename", "default.mab");
user_pref("ldap_2.servers.default.replication.lastChangeNumber", 0);
user_pref("ldap_2.servers.default.uri", "moz-abldapdirectory://default.mab");
user_pref("ldap_2.servers.history.replication.lastChangeNumber", 0);
user_pref("ldap_2.servers.pab.replication.lastChangeNumber", 0);
user_pref("mail.account.account1.server", "server1");
user_pref("mail.account.account2.identities", "id1");
user_pref("mail.account.account2.server", "server2");
user_pref("mail.accountmanager.accounts", "account1,account2");
user_pref("mail.accountmanager.defaultaccount", "account2");
user_pref("mail.accountmanager.localfoldersserver", "server1");
user_pref("mail.attachment.store.version", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.identity.id1.directoryServer", "ldap_2.servers.OracleDirectory");
user_pref("mail.identity.id1.doBcc", false);
user_pref("mail.identity.id1.doBccList", "");
user_pref("mail.identity.id1.draft_folder", "imap://gourav.s.sarkar%40oracle.com@stbeehive.oracle.com/Drafts");
user_pref("mail.identity.id1.drafts_folder_picker_mode", "0");
user_pref("mail.identity.id1.escapedVCard", "");
user_pref("mail.identity.id1.fcc_folder", "imap://gourav.s.sarkar%40oracle.com@stbeehive.oracle.com/Sent");
user_pref("mail.identity.id1.fcc_folder_picker_mode", "0");
user_pref("mail.identity.id1.fullName", "");
user_pref("mail.identity.id1.organization", "Oracle Corporation");
user_pref("mail.identity.id1.overrideGlobal_Pref", true);
user_pref("mail.identity.id1.reply_on_top", 1);
user_pref("mail.identity.id1.reply_to", "");
user_pref("mail.identity.id1.smtpServer", "smtp1");
user_pref("mail.identity.id1.stationery_folder", "imap://gourav.s.sarkar%40oracle.com@stbeehive.oracle.com/Templates");
user_pref("mail.identity.id1.tmpl_folder_picker_mode", "0");
user_pref("mail.identity.id1.useremail", "gourav.s.sarkar@oracle.com");
user_pref("mail.identity.id1.valid", true);
user_pref("mail.root.imap", "/home/gosarkar/.thunderbird/default.brd/ImapMail");
user_pref("mail.root.imap-rel", "[ProfD]ImapMail");
user_pref("mail.root.none", "/home/gosarkar/.thunderbird/default.brd/Mail");
user_pref("mail.root.none-rel", "[ProfD]Mail");
user_pref("mail.server.server1.directory", "/home/gosarkar/.thunderbird/default.brd/Mail/Local Folders");
user_pref("mail.server.server1.directory-rel", "[ProfD]Mail/Local Folders");
user_pref("mail.server.server1.hostname", "Local Folders");
user_pref("mail.server.server1.name", "Local Folders");
user_pref("mail.server.server1.type", "none");
user_pref("mail.server.server1.userName", "nobody");
user_pref("mail.server.server2.capability", 528417);
user_pref("mail.server.server2.check_time", 5);
user_pref("mail.server.server2.directory", "/home/gosarkar/.thunderbird/default.brd/ImapMail/stbeehive.oracle.com");
user_pref("mail.server.server2.directory-rel", "[ProfD]ImapMail/stbeehive.oracle.com");
user_pref("mail.server.server2.download_on_biff", true);
user_pref("mail.server.server2.hostname", "stbeehive.oracle.com");
user_pref("mail.server.server2.login_at_startup", true);
user_pref("mail.server.server2.max_cached_connections", 5);
user_pref("mail.server.server2.name", "gourav.s.sarkar@oracle.com");
user_pref("mail.server.server2.port", 993);
user_pref("mail.server.server2.socketType", 3);
user_pref("mail.server.server2.type", "imap");
user_pref("mail.server.server2.userName", "gourav.s.sarkar@oracle.com");
user_pref("mail.smtp.defaultserver", "smtp1");
user_pref("mail.smtpserver.smtp1.auth_method", 1);
user_pref("mail.smtpserver.smtp1.hostname", "stbeehive.oracle.com");
user_pref("mail.smtpserver.smtp1.port", 465);
user_pref("mail.smtpserver.smtp1.try_ssl", 3);
user_pref("mail.smtpserver.smtp1.username", "gourav.s.sarkar@oracle.com");
user_pref("mail.smtpservers", "smtp1");
user_pref("mail.spam.version", 1);
user_pref("mail.startup.enabledMailCheckOnce", true);
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "1.8.1.17");
user_pref("mailnews.ui.threadpane.version", 5);
user_pref("network.proxy.autoconfig_url", "http://wpad/wpad.dat");
user_pref("network.proxy.type", 2);
user_pref("wallet.caveat", true);
user_pref("network.tcp.sendbuffer", 65536);
